services:
  - type: web
    name: salon-backend
    env: docker
    repo: https://github.com/sbabatunde/Salon-Backend
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/storage/app/precious_hairmpire.sqlite